// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.5.0
// source: push/push_server.proto

package push

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_NONE      EventType = 0
	EventType_HEARTBEAT EventType = 1
	EventType_TEXT      EventType = 100
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:   "NONE",
		1:   "HEARTBEAT",
		100: "TEXT",
	}
	EventType_value = map[string]int32{
		"NONE":      0,
		"HEARTBEAT": 1,
		"TEXT":      100,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_push_push_server_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_push_push_server_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_push_push_server_proto_rawDescGZIP(), []int{0}
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq       uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	EventType uint32 `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // EventType
	// data field
	Text string `protobuf:"bytes,100,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_push_push_server_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetEventType() uint32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *Event) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// The request message containing the user's name.
type StartPushReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *StartPushReq) Reset() {
	*x = StartPushReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartPushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPushReq) ProtoMessage() {}

func (x *StartPushReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPushReq.ProtoReflect.Descriptor instead.
func (*StartPushReq) Descriptor() ([]byte, []int) {
	return file_push_push_server_proto_rawDescGZIP(), []int{1}
}

func (x *StartPushReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// The response message containing the greetings
type StartPushRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StartPushRsp) Reset() {
	*x = StartPushRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartPushRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPushRsp) ProtoMessage() {}

func (x *StartPushRsp) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPushRsp.ProtoReflect.Descriptor instead.
func (*StartPushRsp) Descriptor() ([]byte, []int) {
	return file_push_push_server_proto_rawDescGZIP(), []int{2}
}

func (x *StartPushRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BatchPushReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UidList   []string `protobuf:"bytes,1,rep,name=uid_list,json=uidList,proto3" json:"uid_list,omitempty"`
	EventList []*Event `protobuf:"bytes,2,rep,name=event_list,json=eventList,proto3" json:"event_list,omitempty"`
}

func (x *BatchPushReq) Reset() {
	*x = BatchPushReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchPushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPushReq) ProtoMessage() {}

func (x *BatchPushReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPushReq.ProtoReflect.Descriptor instead.
func (*BatchPushReq) Descriptor() ([]byte, []int) {
	return file_push_push_server_proto_rawDescGZIP(), []int{3}
}

func (x *BatchPushReq) GetUidList() []string {
	if x != nil {
		return x.UidList
	}
	return nil
}

func (x *BatchPushReq) GetEventList() []*Event {
	if x != nil {
		return x.EventList
	}
	return nil
}

type BatchPushRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuccUidList   []string `protobuf:"bytes,1,rep,name=succ_uid_list,json=succUidList,proto3" json:"succ_uid_list,omitempty"`
	FailedUidList []string `protobuf:"bytes,2,rep,name=failed_uid_list,json=failedUidList,proto3" json:"failed_uid_list,omitempty"`
}

func (x *BatchPushRsp) Reset() {
	*x = BatchPushRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchPushRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPushRsp) ProtoMessage() {}

func (x *BatchPushRsp) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPushRsp.ProtoReflect.Descriptor instead.
func (*BatchPushRsp) Descriptor() ([]byte, []int) {
	return file_push_push_server_proto_rawDescGZIP(), []int{4}
}

func (x *BatchPushRsp) GetSuccUidList() []string {
	if x != nil {
		return x.SuccUidList
	}
	return nil
}

func (x *BatchPushRsp) GetFailedUidList() []string {
	if x != nil {
		return x.FailedUidList
	}
	return nil
}

var File_push_push_server_proto protoreflect.FileDescriptor

var file_push_push_server_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x75, 0x73, 0x68, 0x2f, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70, 0x75, 0x73, 0x68, 0x22, 0x4c,
	0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x20, 0x0a, 0x0c,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x28,
	0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x75, 0x73, 0x68, 0x52, 0x73, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x55, 0x0a, 0x0c, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x69, 0x64, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x69, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0x5a, 0x0a, 0x0c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x50, 0x75, 0x73, 0x68, 0x52, 0x73, 0x70, 0x12,
	0x22, 0x0a, 0x0d, 0x73, 0x75, 0x63, 0x63, 0x5f, 0x75, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x75, 0x63, 0x63, 0x55, 0x69, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x5f, 0x75, 0x69,
	0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x61,
	0x69, 0x6c, 0x65, 0x64, 0x55, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x2a, 0x2e, 0x0a, 0x09, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x48, 0x45, 0x41, 0x52, 0x54, 0x42, 0x45, 0x41, 0x54, 0x10,
	0x01, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54, 0x10, 0x64, 0x32, 0x7a, 0x0a, 0x0a, 0x50,
	0x75, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x09, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x50, 0x75, 0x73, 0x68, 0x12, 0x12, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x75, 0x73,
	0x68, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x75, 0x73, 0x68, 0x52, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x35, 0x0a, 0x09, 0x42, 0x61, 0x74, 0x63, 0x68, 0x50, 0x75, 0x73, 0x68, 0x12, 0x12, 0x2e,
	0x70, 0x75, 0x73, 0x68, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65,
	0x71, 0x1a, 0x12, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x50, 0x75,
	0x73, 0x68, 0x52, 0x73, 0x70, 0x22, 0x00, 0x42, 0x27, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x68, 0x6f, 0x75, 0x6a, 0x69, 0x61, 0x77, 0x65, 0x69,
	0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x75, 0x73, 0x68, 0x80, 0x01, 0x01,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_push_push_server_proto_rawDescOnce sync.Once
	file_push_push_server_proto_rawDescData = file_push_push_server_proto_rawDesc
)

func file_push_push_server_proto_rawDescGZIP() []byte {
	file_push_push_server_proto_rawDescOnce.Do(func() {
		file_push_push_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_push_push_server_proto_rawDescData)
	})
	return file_push_push_server_proto_rawDescData
}

var file_push_push_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_push_push_server_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_push_push_server_proto_goTypes = []interface{}{
	(EventType)(0),       // 0: push.EventType
	(*Event)(nil),        // 1: push.Event
	(*StartPushReq)(nil), // 2: push.StartPushReq
	(*StartPushRsp)(nil), // 3: push.StartPushRsp
	(*BatchPushReq)(nil), // 4: push.BatchPushReq
	(*BatchPushRsp)(nil), // 5: push.BatchPushRsp
}
var file_push_push_server_proto_depIdxs = []int32{
	1, // 0: push.BatchPushReq.event_list:type_name -> push.Event
	2, // 1: push.PushServer.StartPush:input_type -> push.StartPushReq
	4, // 2: push.PushServer.BatchPush:input_type -> push.BatchPushReq
	3, // 3: push.PushServer.StartPush:output_type -> push.StartPushRsp
	5, // 4: push.PushServer.BatchPush:output_type -> push.BatchPushRsp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_push_push_server_proto_init() }
func file_push_push_server_proto_init() {
	if File_push_push_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_push_push_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartPushReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartPushRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchPushReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchPushRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_push_push_server_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_push_push_server_proto_goTypes,
		DependencyIndexes: file_push_push_server_proto_depIdxs,
		EnumInfos:         file_push_push_server_proto_enumTypes,
		MessageInfos:      file_push_push_server_proto_msgTypes,
	}.Build()
	File_push_push_server_proto = out.File
	file_push_push_server_proto_rawDesc = nil
	file_push_push_server_proto_goTypes = nil
	file_push_push_server_proto_depIdxs = nil
}
